### ISSUE TITLE
service doesn't run because "Failed to parse service restart specifier, ignoring: False"

### ISSUE THREAD

**Issue by timblaktu** [cimon-io/ansible-role-systemd-service#14]
The following role invocation using Ansible 2.9.10 on Debian Stretch controller:

```
- name: >
    Install systemd service unit to generate /dev/loop nodes on startup.
    (rc.local is disabled in Debian Buster in lieu of systemd.)
  become: true
  hosts: engineering_services_jenkins_cluster
  vars:
    - systemd_service:
        create-loop-devices:
          description: Oneshot service unit to create loop devices at boot.
          enabled: Yes
          exec_start: "/bin/bash -lc '/usr/local/bin/create-loop-devices.sh'"
          user: root
          group: root
          type: oneshot
          restart: no
  roles:
    - role: cimon-io.systemd_service
```

Results in the following service unit on the controlled (Debian Buster) machine: 

```
[Unit]
Description="Oneshot service unit to create loop devices at boot."

[Service]
Type=oneshot
RestartSec=30
Restart=False
User=root
Group=root
ExecStart=/bin/bash -lc '/usr/local/bin/create-loop-devices.sh'
```

which results in the following syslog entry in the controlled machine:

```
systemd[1]: /etc/systemd/system/create-loop-devices.service:6: Failed to parse service restart specifier, ignoring: False
```

Expected behavior is that the default "restart: no" would result in a valid "restart" setting in the systemd service file. [The man page](https://man7.org/linux/man-pages/man5/systemd.service.5.html) says that Restart:

> Takes one of no, on-success, on-failure, on-abnormal, on-watchdog, on-abort, or always. 

As a test, I changed my role to not specify a "restart" parameter, and then, and only then did my service actually run.
